<?php
    $scriptList = array("jquery-1.11.3.min.js", "carousel.js");
   
    include("restricted/header.php");
    ?>

    <div id="main">
        <p>
            Welcome to Classic Cinema, your online store for classic film.
        </p>
        <div id="carousel">
            <!-- Content generated by JavaScript in carousel.js -->
        </div>
    </div>


    <?php include ("restricted/footer.php"); ?>
